# Generated by Django 5.0.14 on 2025-11-03 21:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_story_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 4, 21, 39, 39, 925954, tzinfo=datetime.timezone.utc)),
        ),
    ]
