# Generated by Django 5.0.14 on 2025-11-04 23:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_story_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 5, 23, 22, 26, 219513, tzinfo=datetime.timezone.utc)),
        ),
    ]
