# Generated by Django 5.0.14 on 2025-11-05 22:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_story_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 6, 22, 27, 56, 272140, tzinfo=datetime.timezone.utc)),
        ),
    ]
