# Generated by Django 5.0.14 on 2025-11-06 19:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_story_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 7, 19, 43, 22, 527678, tzinfo=datetime.timezone.utc)),
        ),
    ]
