# Generated by Django 5.0.14 on 2025-11-07 21:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_story_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 8, 21, 25, 41, 518502, tzinfo=datetime.timezone.utc)),
        ),
    ]
