# Generated by Django 5.0.14 on 2025-11-24 09:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicationstatusnotification',
            name='status',
            field=models.CharField(choices=[('pending', 'Kutilmoqda'), ('approved', 'Tasdiqlandi'), ('rejected', 'Rad etildi')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentform',
            name='extra_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='applicationstatusnotification',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='applications.application'),
        ),
        migrations.AlterField(
            model_name='loginpassword',
            name='password',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='studentform',
            name='application',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='form', to='applications.application'),
        ),
        migrations.AlterField(
            model_name='studentform',
            name='full_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='studentform',
            name='phone_number',
            field=models.CharField(max_length=30),
        ),
    ]
