# Generated by Django 5.0.14 on 2025-11-07 21:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0006_subject_alter_teacher_subject'),
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['-start_time'], 'permissions': [('can_add_course', "Kurs qo'shish huquqi")], 'verbose_name': 'Kurs', 'verbose_name_plural': 'Course'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_at'], 'verbose_name': 'Sharh', 'verbose_name_plural': 'Comments'},
        ),
        migrations.AlterField(
            model_name='course',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject_courses', to='center.subject'),
        ),
    ]
