# Generated by Django 5.0.14 on 2025-11-12 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_remove_course_title_course_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homework',
            name='description',
        ),
        migrations.AddField(
            model_name='homework',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
