# Generated by Django 5.0.14 on 2025-11-12 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_remove_homework_description_homework_files'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homework',
            name='created_by',
        ),
    ]
