# Generated by Django 5.0.14 on 2025-11-04 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='center',
            name='subject',
        ),
        migrations.AddField(
            model_name='center',
            name='subjects',
            field=models.ManyToManyField(related_name='centers', to='center.subject'),
        ),
    ]
