# Generated by Django 5.0.14 on 2025-11-04 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0002_subject_remove_center_subject_center_subjects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='center',
            name='subjects',
        ),
        migrations.AddField(
            model_name='center',
            name='subject',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
