# Generated by Django 5.0.14 on 2025-11-08 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0007_alter_center_options_alter_location_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='center',
            name='subject',
        ),
        migrations.AddField(
            model_name='center',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='centers', to='center.subject'),
        ),
    ]
