# Generated by Django 5.0.14 on 2025-11-09 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0009_teacher_first_name_teacher_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
