# Generated by Django 5.0.14 on 2025-12-01 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0010_teacher_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='center',
            name='subjects',
        ),
    ]
