# Generated by Django 5.0.14 on 2025-12-01 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0011_remove_center_subjects'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='first_name',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='last_name',
        ),
    ]
