# Generated by Django 5.0.14 on 2025-11-28 05:46

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='schedule',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('dushanba', 'Dushanba'), ('seshanba', 'Seshanba'), ('chorshanba', 'Chorshanba'), ('payshanba', 'Payshanba'), ('juma', 'Juma'), ('shanba', 'Shanba'), ('yakshanba', 'Yakshanba')], max_length=200),
        ),
    ]
